### ISSUE TITLE
A/P causes large XTK error on long legs

### ISSUE THREAD

**Issue by scrvl** [it0uchpods/IDG-A33X#6]
### Expected Behavior
Autopilot should follow direct route between fixes

### Current Behavior
Plane drifts several nm off course

### Possible Solution
Could it be the a/p calulates the heading between waypoints based on a 2D surface rather than a 3D sphere? Just a guess.

### Steps to Reproduce
I noticed this on a 300 nm leg, the cross track error here was more than 10 nm at the halfway point.

![nd](https://user-images.githubusercontent.com/34400425/33797566-a95ef9b4-dd0a-11e7-9b45-69a19fd4230e.png)

(Also the naming of lon/lat fixes needs to be changed, the proper format above would be 6140N)

**Comment by it0uchpods** [comment]
No, it's because it only knows the direction of the waypoint from the current position. I have not yet worked out how to track the line on the ND perfectly, so it does have a slight error sometimes. It does however, have the advantage, of dealing with crosswinds decently.

The FMGC is working the way I programmed it, so I'm closing the issue, but don't worry -- it is on my todo list to correctly track this line.

Kind Regards,
Josh
